### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by hahwul** [hahwul/oxtopus#1]
- [ ] Add Schema
- [ ] Add XSS List
- [ ] Add XSS List > Logs
- [ ] Recheck function
- [ ] Custom Payload Recheck check function 
- [ ] End of tool plan
